### ISSUE TITLE
Ouvrir l'année scolaire 2024-2025

### ISSUE THREAD

**Issue by gtournadre** [betagouv/aplypro#1148]
```[tasklist]
### Tasks
- [x] Inégrer Ecole Martime de Mayotte #517
- [x] Intégrer Institut des jeunes Sourds
- [x] Intégrer Collèges de Mayotte qui proposent un CAP #1156
- [x] Fermer les scolarités de 2023-2024 qui ont une date de fin nulle #1160
- [x] Valider la fonctionnalité de report de DA
- [x] Créer une année scolaire 2024-2025 #1140 #1141
- [x] Charger les MEF éligibles 2024-2025 #1064
- [x] Charger les montants journaliers et les plafonds 2024-2025 #1143
- [x] Valider l'appel à Fregata (Mapper) #1131
- [x] Valider l'appel à Sygne (Mapper) #1149
- [ ] Débloquer l'appel à Sygne #1118
- [x] Annoncer dans APLyPro l'ouverture de l'année 2024-2025 #1163
```

**Comment by gtournadre** [comment]
#1143 
#1140 
#1149 
#1141
