### ISSUE TITLE
Retrait de DA

### ISSUE THREAD

**Issue by gtournadre** [betagouv/aplypro#1249]
Il s'agit d'une fonctionnalité qui permet d'enlever le droit avec effet retro-actif. 
L'abrogation de DA met fin au droit en même temps que la fin de la scolarité. Le retrait retire le droit. 
Principe : 
1. Le retrait de DA est lié à la scolarité
- Comme pour la DA ou l'Abrogation, le retrait de DA est un document PDF qui doit être téléchargeable. 
- Le retrait de DA est lié à la Scolarité. Sa génération doit se faire via un bouton depuis la page élève ou depuis la liste des élèves d'une classe. 
- Le Retrait ne peut se faire que si une DA existe et il faut garder une trace en base de la DA qui a existé.
- Il est possible de faire un retrait de DA même quand celle-ci est abrogée.  
- Quelque-soit le MEF sur lequel est la scolarité, son taux journalier et son plafond doivent passer à 0. 

2. Conséquence d'un retrait de DA sur les PFMP 
- Idéalement, il ne faut pas pouvoir créer des PFMP sur une scolarité qui a fait l'objet d'une retrait de DA. 
- Si un retrait est créé sur une scolarité sans PFMP alors aucune action complémentaire. 
- Si un retrait est créé sur une scolarité avec des PFMP : 
   - Les PFMP pending ou incomplete ne peuvent plus être validées
   - Les PFMP validated : 
      - Supprimer les Payment Request donc la transition est pending / Ready / incomplete
      - Laisser les autres. 
      -
3. Comportement vis à vis des PFMP déjà payées
Si des PFMP ont été payées sur une scolarité faisant l'objet d'un retrait de DA : 
- PAsser le montant et le nombre de jours de la PFMP 0
- Passer la PFMP à "rectified"
- Générer une payment request qui sera envoyé à l'ASP pour générer un ordre de reversement. 

4. Comportement avec les PFMP en cours de traitement côté ASP au moment du retrait
Il y a un choix à faire, mais on ne peut pas connaître l'état du retour en avance. Donc soit adapter le parser des retour ASP en anticipant toutes les situation possible. Soit faire des procédure d'analyse des données à postériori. 
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/aplypro/issues/1293
- [ ] https://github.com/betagouv/aplypro/issues/1294
- [ ] https://github.com/betagouv/aplypro/issues/1295
```
