### ISSUE TITLE
Relancer les jobs de Décision d'Attribution des établissements en attente

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [betagouv/aplypro#207]
```[tasklist]
### Tasks
- [x] Avoir une méthode de monitoring efficace
- [x] Kill tous les Jobs de DA en cours
- [x] scale up le nombre de workers
- [x] relancer les jobs de DA de tous les établissements `generating_attributive_decisions: true` (134 à priori)
- [x] monitorer la génération des DA
- [x] scale down le nombre de workers
```

**Comment by DiffusionAplyPro** [comment]
https://sesam.in.orion.education.fr/sesam/view.php?id=456097

**Comment by JeSuisUnCaillou** [comment]
On a identifié un bug supplémentaire à régler avant de pouvoir relancer tous les jobs : Les étudiants homonymes peuvent générer des fichiers avec le même nom, si ces fichiers sont générés le même jour.

**Comment by JeSuisUnCaillou** [comment]
Fix en cours : https://github.com/betagouv/aplypro/pull/237

**Comment by JeSuisUnCaillou** [comment]
Tous les jobs ont été relancés. Parmi les 136 établissements concernés, 132 sont désormais à 100% de DA présentes. J'investigue les 4 derniers.
