### ISSUE TITLE
Pouvoir gérer les élèves avec une schooling fermée

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [betagouv/aplypro#284]
Pour le moment APLyPro n'affiche que les scolarités actives des élèves. Il faudrait pouvoir gérer aussi les scolarités passées, pour y attacher une PFMP, la remplir et la valider même après que l'élève ait changé de classe ou d'établissement.

Ca se traduit par :
- Afficher dans une classe une section "anciens élèves" à part
- ~Afficher dans un élève une section "Anciennes scolarités dans le même établissement" et leurs pfmps~ En fait non, on montre les pfmps de la classe du breadcrumb et c'est tout
```[tasklist]
### Tasks
- [x] Afficher une section "Eleves sortis de la classe" dans la page d'une classe
- [x] Permettre la création de PFMP pour une schooling fermée
- [x] Afficher les schoolings fermées (de la classe) d'un étudiant dans son show
- [x] Afficher l'info de sortie de la classe dans la page de complétion de PFMPs pour toute une classe
- [x] Afficher les élves sortis de classe dans la page de validation de PFMPS
- [x] (et dans le compteur dans la liste des classes à valider)
- [x] Modifier les compteurs de la page d'une classe pour prendre en compte les PFMPs de schoolings fermée
- [x] Ajouter les sortis de classe dans l'interface de création de RIBs en masse
- [x] Permettre la génération de décisions d'attributions pour les élèves avec un schooling fermée
- [x] Modifier les compteurs RIB & DA & PFMPs de la page d'acceuil pour prendre en compte les PFMPs de schoolings fermée
- [x] Modifier les compteurs RIB & DA de la page de liste des classe pour prendre en compte les PFMPs de schoolings fermée
- [x] (et des classes à valider)
- [x] Spécifier "PFMPs de la calsse <label>" dans le show d'un élève
- [x] Show d'un élève : Afficher que l'élève est sorti de la classe si c'est le cas
- [x] mettre en valeur la mention "Sortie de classe" dans les listes
- [x] info "les élèves sortis de classe sont pris en compte dans le compteur"
```

**Comment by DiffusionAplyPro** [comment]
pour suivi : https://sesam.in.orion.education.fr/sesam/view.php?id=458668

**Comment by freesteph** [comment]
Je crois que cette requête représente le nombre total distinct d'élèves avec un schooling fermé :
```ruby
Student.joins(:schoolings).where("schoolings.end_date IS NOT NULL").count => 34895
```

Il faudrait affiner en distinguant ceux qui ont _aussi_ un schooling ouvert, mais je pose ça là en attendant.

**Comment by JeSuisUnCaillou** [comment]
Prévenir la Degesco et le support de la mise à jour quand ça sera en prod.
