### ISSUE TITLE
Rendre visible les pfmps déjà validées et afficher leur status de paiement

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [betagouv/aplypro#365]
Afficher les statuts d'état de paiement une fois accessibles côté ASP
```[tasklist]
### Tasks
- [x] cacher les badges de pfmp si pas de count
- [x] afficher le statut de payment requests dans une pfmp
- [x] Empêcher les actions du show d'une pfmp en fonction du statut de la pfmp ou de son payment (same pour les autres lien d'edit de pfmp, genre dans l'écran de validation par classe)
- [x] Affichage des status de paiements dans la home
- [ ] Affichage des statuts de paiements dans la liste des classes,  la liste des élèves d'une classe, et la liste des pfmps d'un élève
- [ ] Renommer le menu en juste "Paiements"
- [ ] Lister les classes avec PFMPs validées et leur montant global dans la page de paiements
- [ ] Cacher la liste des classes à envoyer en paiement si y'en a aucune
- [ ] dans la page d'envoi en paiements d'une classe, afficher la liste des paiements en cours
- [ ] cacher le form d'envoi si y'en a aucun à valider
- [ ] pouvoir demander le renvoi d'une pfmp en paiement
- [ ] Afficher les raisons du statut "Bloquée"
```

**Comment by AlainSN2** [comment]
Cf. #484

**Comment by JeSuisUnCaillou** [comment]
## Résumé du besoin selon moi

En tant que personnel d'établissement, je veux pouvoir suivre les paiments en cours que j'ai envoyés, ainsi que les échecs.

Je m'attend à avoir ce genre d'information dans la page "Envoyer en paiement", car c'est ici que j'ai validé mes pfmps classe par classe pour les envoyer en paiement.

Je suis habitué à gérer mes élèves par classe, nottamment par ce que mes élèves partent souvent en stage classe par classe.

Je veux rapidement voir les échecs et les raisons de ces échecs, pour corriger mes saisies si besoin.

**Comment by JeSuisUnCaillou** [comment]
Renommer la page "envoyer en paiment" en juste "Paiements".

Y afficher plusieurs tableaux comme suit (si un tableau est vide on ne l'affiche pas) :

![Image](https://github.com/betagouv/aplypro/assets/6117264/7e8a9e17-d21e-489e-b783-0ee139561225)

**Comment by JeSuisUnCaillou** [comment]
Nouvelle proposition plus précise :

# Page de paiments

1. Lien "Demandes de paiements en échecs"
2. Lien "PFMPs à valider" -> page des classes à valider actuelle
3. Lien "Demandes de paiements en cours"
4. Lien "Demandes payées"

Le DSFR : https://www.systeme-de-design.gouv.fr/

**Comment by gtournadre** [comment]
Il serait intéressant d'ajouter une barre de recherche dans cette page, pour que le CE puisse rechercher une info pour un nom de bénéficiaire.
