### ISSUE TITLE
regénérer les DA des établissements avec mauvais directeurs

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [betagouv/aplypro#369]
```[tasklist]
### Tasks
- [x] 0610019P : Mme Cindy GADDINI
- [x] 0910631S : Madame VRAY Catherine
- [x] 0080008R : M. Jean-Marie Amel
```
