### ISSUE TITLE
Déplacer S3 de OVH à Outscale

### ISSUE THREAD

**Issue by jdauphant** [betagouv/aplypro#453]
```[tasklist]
### Tasks
- [ ] Demander à Outscale la création de compte
- [ ] Faire le plan de droits des buckets
- [ ] Configurer des buckets S3 pour AplyPro
- [ ] Migrer les datas
- [ ] Configurer l'app vers les nouveaux buckets
```

**Comment by jdauphant** [comment]
@JeSuisUnCaillou je mets dans la phase industrialisation car pour les paiements manuels, on peut envoyer les DA à la main s'il le faut à l'ASP

**Comment by pskl** [comment]
Est-ce toujours d'actualité et si oui est-ce que l'on a des paramètres en plus sur ce sujet @jdauphant ? 

Timeline, contact, etc ?

Merci

**Comment by JeSuisUnCaillou** [comment]
Honnêtement aucune idée.

D'instinct je dirais que c'est une décision à prendre par la DNE (ou par toi si ils veulent te la déléguer), qui a désormais la responsabilité complète du projet.
