### ISSUE TITLE
Abrogation d'une DA

### ISSUE THREAD

**Issue by AlainSN2** [betagouv/aplypro#461]
Evènements qui rendent caduque une DA :

- Changement d'établissement : 
Sortie de l'établissement = DA abrogée (nouveau document à intégrer) à la date de sortie. Les PFMP antérieures doivent néanmoins être payées. Implique de gérer l'historique des scolarités par établissement.
Attention : conditionner la génération de la nouvelle DA dans le nouvel établissement à l'abrogation de la DA dans l'établissement initial. 
Entrée dans le nouvel établissement : génération d'une nouvelle DA.
- Changement de formation :
Comme pour le changement d'établissement la DA initiale devient caduque et est à abroger s'il y a changement de formation (au sens MEF).  Le chef d'établissement du nouvel établissement ne doit pas pouvoir éditer la DA de l'élève qui vient de l'autre établissement tant que cette dernière n'est pas abrogée. Cela implique de prévoir une notification du CE au niveau du bloc 1 de la page d'accueil : à préciser. 
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/aplypro/issues/903
- [ ] Nettoyer les PFMP : bien associer chaque PFMP à la Schoolings dont les dates de début et de fin incluent la PFMP
- [ ] Afficher dans la vue des classe : comment sont affichés les élèves scolarisés et ceux "sortis de la classe". S'assurer de la validité des dates affichées
- [ ] Au lancement d'APLyPro : Lancer {uai}/LISTE-ELEVES avec paramètres etat-scolarisation = true et une autre avec etat-scolarisation = False (donnera les élèves sortis dans l'année scolaire en cours)
- [ ] A l'affichage d'une classe : Fetch_Student_Information_Job
- [ ] https://github.com/betagouv/aplypro/issues/912
- [ ] https://github.com/betagouv/aplypro/issues/913
- [ ] https://github.com/betagouv/aplypro/issues/958
- [ ] https://github.com/betagouv/aplypro/issues/959
- [ ] https://github.com/betagouv/aplypro/issues/970
```

**Comment by AlainSN2** [comment]
Voir possibilité d'automatiser le process d'abrogation au moment de la sortie de l'établissement en récupérant les coordonnées du CE.
Nouvel établissement :
Informer le nouvel établissement que des élèves viennent d’autres établissement et que des DA n’ont pas encore été abrogées dans l’établissement précédent et empêcher la génération de la nouvelle DA tant que la DA de l'établissement précédent n'a pas été abrogée.

**Comment by JeSuisUnCaillou** [comment]
En attendant la création de ces abrogations, on ne sélectionne que les "premières" scolarités des élèves dont l'on paye les PFMPs.

**Comment by AlainSN2** [comment]
Pour prioriser : essayer d'estimer le nombre d'élèves ne seraient pas payés (DA abrogé) si on bloquait les paiements postérieurs au changement de situation : @DiffusionAplyPro help  !

**Comment by DiffusionAplyPro** [comment]
```SQL
select et.ACADEMY_LABEL,et.UAI,et.NAME,s.INE,s.LAST_NAME,s.FIRST_NAME,s.BIRTHDATE,c.LABEL DIVISION,sco.END_DATE,sco.ATTRIBUTIVE_DECISION_VERSION,COUNT(PFMP.ID)NB_PFMP,COUNT(P.ID) NB_VALIDE
from public.schoolings sco
join public.STUDENTS s on s.ID = sco.ID
join public.CLASSES c on c.id = sco.CLASSE_ID
join public.ESTABLISHMENTS et on et.id = c.ESTABLISHMENT_ID
join public.PFMPS pfmp on pfmp.SCHOOLING_ID = sco.id
left join public.PAYMENTS p on p.PFMP_ID = pfmp.id
where SCO.END_DATE is not null
and sco.ATTRIBUTIVE_DECISION_VERSION !=0
GROUP BY et.ACADEMY_LABEL,et.UAI,et.NAME,s.INE,s.LAST_NAME,s.FIRST_NAME,s.BIRTHDATE,c.LABEL,sco.END_DATE,sco.ATTRIBUTIVE_DECISION_VERSION
order by et.ACADEMY_LABEL,et.UAI,et.NAME,s.LAST_NAME,s.FIRST_NAME,s.BIRTHDATE,c.LABEL,sco.END_DATE;
```

Actuellement 10 132 élèves avec une scolarité fermée ayant au moins une PFMP saisie.

**Comment by JeSuisUnCaillou** [comment]
Le modèle d'abrogation de DA : 

[Modèle Abrogation DAA.docx](https://github.com/betagouv/aplypro/files/15237408/Modele.Abrogation.DAA.docx)

**Comment by JeSuisUnCaillou** [comment]
S'inspirer de [AttributiveDecisionGenerator](https://github.com/betagouv/aplypro/blob/stats_of_payments/lib/attribute_decision_generator.rb) pour créer un générateur d'abrogation de décisions d'attribution.

**Comment by ac-clermont-dylan** [comment]
Premier jet :
```
1.1 - Départ d'établissement (uai : unité administrative immatriculée)
        - L'établissement A doit pouvoir Abroger une DA
        - L'établissement A doit avoir une alerte sur les DA a abroger	

1.2 - Récupération d'un élène par un établissement
	- Formation éligible :
		- L'établissement B doit avoir une alerte mentionnant le blocage de l'édition de la DA dans l'attente de l'abrogation par l'établissement A

2 - Changement de formation (MEF)
	- Dans le même établissement
		- L'établissement doit pouvoir Abroger une DA
		- L'établissement doit avoir une alerte sur les DA a abroger

		- La nouvelle formation est-elle éligible ?
			- Oui : Pouvoir éditer une nouvelle DA
			
			- Non : N/A
	
	- Dans un autre établissement
		- L'établissement A doit pouvoir Abroger une DA
		- L'établissement A doit avoir une alerte sur les DA a abroger

		- La nouvelle formation est-elle éligible ?
			- Oui : 
				- Pouvoir éditer une nouvelle DA
				- L'établissement B doit avoir une alerte mentionnant le blocage de l'édition de la DA dans l'attente de l'abrogation par l'établissement A
			
			- Non : N/A

3 - Changement de statut
	- Dans le même établissement (Scolaire vers Apprenti ou autre)
		- L'établissement doit pouvoir Abroger une DA
		- L'établissement doit avoir une alerte sur les DA a abroger

	- Dans le même établissement (Apprenti ou autre vers Scolaire)
		- N/A cas initial déjà géré

	- Dans un autre établissement (Scolaire vers Apprenti ou autre)
		- L'établissement doit pouvoir Abroger une DA
		- L'établissement doit avoir une alerte sur les DA a abroger

	- Dans un autre établissement (Apprenti ou autre vers Scolaire)
		- N/A cas initial déjà géré

4 - Changement d'année
	- Déja traité car la DA concenne et mentionne une année scolaire


ToDo :
- Vérifier le mécanisme empéchant de ganérer une DA si la formation n'est pas éligible alors que l'élève est déjà connu en base aplypro
```

**Comment by gtournadre** [comment]
```[tasklist]
### Tasks
- [ ] Rapatrier les vraies dates de début et de fin des scolarités
- [ ] 
```
