### ISSUE TITLE
contrainte sur la présence d'une DA avant validation (la DA avant tout)

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [betagouv/aplypro#498]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/aplypro/issues/593
- [x] Empêcher la validation d'une PFMP si la DA est manquante
- [x] Empêcher la validation d'une PFMP si les coordonnées bancaires sont manquantes
```

**Comment by pskl** [comment]
Rendre cette condition nécessaire avant tout autre action (génération des DAs puis invitations des DAs)

**Comment by JeSuisUnCaillou** [comment]
Amen.
