### ISSUE TITLE
RIBs aux noms trop longs

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [betagouv/aplypro#611]
L'ASP veut un max de 32 caractères pour le nom d'un rib.

```ruby
Rib.where("LENGTH(name) > 32").count
# => 9710
```

```[tasklist]
### Tasks
- [ ] Ajouter une contrainte de db et de modèle pour éviter d'en saisir des trop longs
- [x] Tronquer le nom lors de la création du fichier pour l'ASP ?
- [ ] Limiter la taille du nom lors de la création d'un RIB ?
```

**Comment by tnicolas1** [comment]
@pskl Cette tâche est faite ?

**Comment by gtournadre** [comment]
Fait depuis le début des paiements en avril
