### ISSUE TITLE
Fixes on AP UI

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [betagouv/aplypro#635]
```[tasklist]
### Tasks
- [x] retirer les numéros techniques ASP inutilisés par les agents
- [x] retirer la recherche par ces numéros techniques
- [x] solidifer la recherche de numéro de DA pour pas qu'il y ait d'effets de bords
```
