### ISSUE TITLE
Erreurs de validation des 7000

### ISSUE THREAD

**Issue by freesteph** [betagouv/aplypro#675]
```
 {"BIC"=>
   "Element '{http://www.cnasea.fr/fichier}BIC': [facet 'maxLength'] The value has a length of '12'; this exceeds the allowed maximum length of '11'., 1871:0:"},
 {"NUMADM"=>
   "Element '{http://www.cnasea.fr/fichier}NUMADM': [facet 'maxLength'] The value has a length of '22'; this exceeds the allowed maximum length of '21'., 15977:0:"},
 {"INTITDEST"=>
   "Element '{http://www.cnasea.fr/fichier}INTITDEST': [facet 'pattern'] The value 'REDACTED\tCeline\t\t' is not accepted by the pattern '[^\\t¨;]*'., 96254:0:"},
 {"PRENOM"=>
   "Element '{http://www.cnasea.fr/fichier}PRENOM': [facet 'maxLength'] The value has a length of '21'; this exceeds the allowed maximum length of '20'., 564669:0:"}]
```

## Problèmes identifiés

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/aplypro/issues/678
- [ ] https://github.com/betagouv/aplypro/issues/677
- [ ] https://github.com/betagouv/aplypro/issues/676
- [ ] https://github.com/betagouv/aplypro/issues/679
```

**Comment by JeSuisUnCaillou** [comment]
On a aussi vu que certaines Schooling avec DA n'avaient pas de numéro administratif

```ruby
Schooling.with_attributive_decisions.where(administrative_number:nil).count
# => 9016
```
