### ISSUE TITLE
Gestion de l'année scolaire

### ISSUE THREAD

**Issue by tnicolas1** [betagouv/aplypro#944]
### Tasks
- [x] https://github.com/betagouv/aplypro/issues/957
- [x] Supprimer toute mention de "Aplypro::SCHOOL_YEAR" et "Aplypro::DEFAULT_SCHOOL_YEAR_START"
- [x] https://github.com/betagouv/aplypro/issues/969
- [x] Modification des Mappers pour prendre en compte l'année scolaire
- [x] https://github.com/betagouv/aplypro/issues/984
- [x] https://github.com/betagouv/aplypro/issues/992
- [x] https://github.com/betagouv/aplypro/issues/1003

**Comment by tnicolas1** [comment]
Merge #497

**Comment by JeSuisUnCaillou** [comment]
Si besoin d'arrêter les récupérations de classes par ce qu'on a pas encore le code pour stocker les nouvelles classes de 2024, commenter cette ligne : https://github.com/betagouv/aplypro/blob/feat/school-year/app/controllers/users/omniauth_callbacks_controller.rb/#L144

**Comment by tnicolas1** [comment]
Note : Réutiliser le système de sélection d'un établissement https://github.com/betagouv/aplypro/blob/8c3056b84f2cf675b550d91a8ea0f95d67c09409/features/step_definitions/perdir_steps.rb#L6

**Comment by JeSuisUnCaillou** [comment]
Dans le modèle `establishment.rb`, on veut que cette méthode prenne une année scolaire en argument : https://github.com/betagouv/aplypro/blob/feat/school-year/app/models/establishment.rb/#L69-L77

Pour qu'elle nous donne la range de l'année scolaire de l'établissement pour l'année donnée. Cela nous permettra de valider qu'une pfmp a des dates de début et de fin **dans l'année scolaire de sa classe**, au lieu de dans l'année scolaire courante, ici : https://github.com/betagouv/aplypro/blob/feat/school-year/app/models/pfmp.rb/#L34-L38
